services:
  ocr-pymupdf:
    build: .
    container_name: ocr-pymupdf
    volumes:
      - ./pdfs:/pdfs
      - ./result:/result
      - ./src:/src
      - ./data:/data
      - ./logs:/logs
      - ./cache:/cache
      - ./output:/output
      - ./static:/static
    stdin_open: true
    tty: true
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app/src
