services:
  ocr-pymupdf:
    build: .
    container_name: ocr-pymupdf
    volumes:
      - ./pdfs:/app/pdfs
      - ./result:/app/result
      - ./src:/app/src
      - ./data:/app/data
      - ./logs:/app/logs
      - ./cache:/app/cache
      - ./output:/app/output
      - ./static:/app/static
      - ./config:/app/config
      - ./uploads:/app/uploads
    stdin_open: true
    tty: true
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app:/app/src
